config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  resources :users do
    resources :lists do
      resources :items
    end
  end

  root 'login#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
  validates :name, presence: true
  
  def change_bool
    self.done = !self.done
  end
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lists, dependent: :destroy
  has_secure_password
  validates :name, presence: true, length: { minimum: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by_id(session[:current_user_id]) if session[:current_user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to root_path unless current_user && @current_user[:id].to_s == params[:user_id]
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  before_filter :authorize
  
  def index
    fill_vars_user_list_item
    @items = @list.items
  end
  
  def show
  end
  
  def new
    @item = Item.new
  end
  
  def create
    fill_vars_user_list
    @item = @list.items.create(item_params)
    if @item.save
      ActionCable.server.broadcast 'items',
        item: @item.name
    end
    redirect_to edit_user_list_path(@user.id, @list.id)
  end
  
  def update
    fill_vars_user_list_item
    @item.change_bool
    if @item.save
      ActionCable.server.broadcast 'items',
        item: @item.name
    end
    redirect_to edit_user_list_path(params[:user_id], params[:list_id])
  end
  
  def destroy
    fill_vars_user_list_item
    if @item.destroy
      ActionCable.server.broadcast 'items',
        item: @item.name
    end
    redirect_to edit_user_list_path(@user.id, @list.id)
  end
  
  def fill_vars_user_list
    @user = current_user
    @list = @user.lists.find_by_id(params[:list_id])
  end
  
  def fill_vars_user_list_item
    fill_vars_user_list
    @item = @list.items.find_by_id(params[:id])
  end
  
  private
  def item_params
    params.require(:item).permit(:name)
  end
  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_filter :authorize, :except => :show

  def index
    @user = current_user
    @lists = @user.lists
  end

  def show
    @user = User.find_by_id(params[:user_id])
    @list = List.find_by_id(params[:id])
    @items = @list.items
  end
  
  def new
    @list = List.new
  end
  
  def edit
    fill_vars_user_lists_list_items
  end
  
  def create
    @list = current_user.lists.create(list_params)
    
    if @list.save
      redirect_to user_lists_path
    else
      render 'index'
    end
  end
  
  def destroy
    fill_vars_user_lists_list
    @list.destroy
    redirect_to user_lists_path
  end
  
  def fill_vars_user_lists_list
    @user = current_user
    @lists = @user.lists
    @list = @lists.find_by_id(params[:id])
  end
  
  def fill_vars_user_lists_list_items
    fill_vars_user_lists_list
    @items = @list.items
  end
  
  private
  def list_params
    params.require(:list).permit(:name)
  end
  
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
  
  def create
  end
  
  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
  
  def create
    @user = User.find_by_name(user_params[:name])
    logger.info "UserController.create user_params[:name]: #{user_params[:name]}"
    logger.debug "User nil" unless @user
    if @user 
      logger.debug "User found, name:  #{@user.name}"
      if @user.authenticate(user_params[:password])
        logger.debug "User loged in succesfully @user.id: #{@user.id}"
        session[:current_user_id] = @user.id
        redirect_to user_lists_path(@user.id)
      else
        logger.info "User (#{@user.name}) log in failure: wrong password"
        #flash.now[:error] = 'User name taken. Wrong passowrd.'
        @user.errors.add(:password, :invalid)
        render "/login/index/"
      end
    else
      @user = User.new(user_params)
      logger.info "Registering new user: #{@user.name}"
      if @user.save
        logger.debug "User (#{@user.name}) succesfully registered"
        session[:current_user_id] = @user.id
        redirect_to user_lists_path(@user.id), notice: 'User succesfully created'
      else
        logger.debug "Error while registering new user"
        #flash.now[:error] = 'An error occured'
        render "/login/index/"
      end
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_for :item, url: user_list_items_path(@user.id, @list.id) do |itm| %>
  <div>
    <%= itm.label :name %><br>
    <%= itm.text_field :name %>
  </div>
  <div>
    <%= itm.submit "Add Task" %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= "Y" if item.done %></td>
        <td><%= item.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tode</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_item_list.html.erb
<h3>Tasks:</h3>
<div>
  <table>
    <tr>
      <th>Done</th>
      <th>Task</th>
      <th>Check / Uncheck</th>
      <th>Delete</th>
      <th colspan="2"></th>
    </tr>
    <% @items.each do |itm| %>
      <tr>
        <div class="panel-body" id="items" data-list=<%= @list.id %>>
          <td><%= "Y" if itm.done %></td>
          <td><%= itm.name %></td>
          <td>
            <%= button_to "Check", user_list_item_path(@user.id, @list.id, itm.id), method: :put %>
          </td>
          <td>
            <%= button_to "Delete", user_list_item_path(@user.id, @list.id, itm.id), method: :delete %>
          </td>
        </div>
      </tr>
    <% end %>
  </table>
</div>

app/views/lists/_public_list_view.html.erb
<h1>Show Your List</h1>
<h2><%= @list.name %></h2>

<h3>Tasks:</h3>
<div>
  <table>
    <tr>
      <th>Done</th>
      <th>Task</th>
      <th colspan="2"></th>
    </tr>
    <% @items.each do |itm| %>
      <tr>
        <td><%= "Y" if itm.done %></td>
        <td><%= itm.name %></td>
      </tr>
    <% end %>
  </table>
</div>
<div>
  <%= link_to "Back", user_lists_path(@user.id)%>
</div>

app/views/lists/edit.html.erb
<h1>Edit Your List</h1>
<h2><%= @list.name %></h2>

<%= render 'item_list' %>

<h3>Add a Task</h3>
<div>
  <%= form_for :item, url: user_list_items_path(@user.id, @list.id) do |itm| %>
    <div>
      <%= itm.label :name %><br>
      <%= itm.text_field :name %>
    </div>
    <div>
      <%= itm.submit "Add Task" %>
    </div>
  <% end %>
</div>
<div>
  <%= link_to "Back To Lists", user_lists_path(@user.id)%>
</div>

app/views/lists/index.html.erb
<h1>Menu</h1>
<div>
User: <%= @user.name %>
<%= link_to "Log Out", root_path %>
</div>
<div>
  <h2>Your Lists</h2>
  <ul><!--List of ToDo lists for current user-->
    <% @lists.each do |lst| %>
      <li>
        <%= lst.name %>
        <%= link_to "Show", user_list_path(@user.id, lst.id) %>
        <%= link_to "Edit", edit_user_list_path(@user.id, lst.id)%>
        <%= button_to "Delete", user_list_path(@user.id, lst.id), method: :delete %>
      </li>
    <% end %>
  </ul>
</div>
<div><!--Form for adding a new list-->
  <h2>Add a List</h2>
  <%= form_for :list, url: user_lists_path do |f| %>

    <% if @list && @list.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:
        </h2>
        <ul>
          <% @list.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>

    <div>
      <%= f.submit "Create List" %>
    </div>
 
  <% end %>
</div>

app/views/lists/show.html.erb
<%= render 'public_list_view' %>

app/views/login/index.html.erb
<h1>ToDe</h1>
<h2>Register or Log in</h2>
<div>
  <%= form_for :user, url: users_path do |f| %>
    
    <% if @user && @user.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@user.errors.count, "error") %> prohibited this user from being registered or authorized:
        </h2>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <div>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
  
    <div>
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
  
    <div>
      <%= f.submit "Submit"%>
    </div>
  <% end %>
</div>
<%= console %>